//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AfterSchool
    {
        public int StudentId { get; set; }
        public int PeriodFrom { get; set; }
        public int PeriodTo { get; set; }
        public string NameOfInstitution { get; set; }
        public string NameOfQualification { get; set; }
        public string StudyComplete { get; set; }
        public string ReferenceNumber { get; set; }
    }
}
