//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolDetail
    {
        public int StudentId { get; set; }
        public string NameOfSchool { get; set; }
        public int HighestGradePassed { get; set; }
        public int TelNumber { get; set; }
        public string SeniorCertificate { get; set; }
        public string MatricExemption { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public int PostalCode { get; set; }
        public int ActiveYear { get; set; }
        public string SubjectName { get; set; }
        public string Standard { get; set; }
        public int Percentage { get; set; }
    }
}
