//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Information
    {
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Initials { get; set; }
        public string Title { get; set; }
        public string Gender { get; set; }
        public string Age { get; set; }
        public string DateOfBirth { get; set; }
        public string IDNumber { get; set; }
        public string HomeLanguage { get; set; }
        public string PassportNumber { get; set; }
        public string Nationality { get; set; }
        public string Race { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    }
}
